### ISSUE TITLE
I have a fix for unicode not writing

### ISSUE THREAD

**Issue by bentito** [bengwall3/Udacity-Transcript-Formatter#1]
Not sure if you need to add me to the project so I can make pull requests?

**Comment by bengwall3** [comment]
I've not done this before -- does assigning you to the issue have the desired effect? (Or maybe you have to fork it first?)

**Comment by bentito** [comment]
I think you should see my pull request from my fork of the project now.

**Comment by bengwall3** [comment]
Looks good! Thanks for providing the fix. Neat to see that someone found this to be useful.
